name: Run application

on:
  schedule:
    # Run at every 15th minute
    - cron:  '15 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache EXEC_TIMETABLE.json file
        id: exec_times
        uses: actions/cache@v2
        with:
          path: exec_timetable
          key: ${{ hashFiles('EXEC_TIMETABLE.json') }}

      - name: Create Credentials and Receivers files
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: |
          echo "$CREDENTIALS" > CREDENTIALS.yaml
          echo "$RECEIVERS" > RECEIVERS.txt

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt 
      
      # delete cat line below, we are using it for debugging purposes
      - name: Run main application
        run: |
          cat exec_timetable/EXEC_TIMETABLE.json
          python3 main.py
          cat exec_timetable/EXEC_TIMETABLE.json
