name: Run application

on:
  # Run every 30 min
  schedule:
    - cron:  "27 18 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Credentials and Receivers files
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: |
          echo "$CREDENTIALS" > CREDENTIALS.yaml
          echo "$RECEIVERS" > RECEIVERS.txt

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt 
      
      - name: Run main application
        run: python3 main.py
