name: Run application

on:
  schedule:
    # Run every 25th minute
    - cron:  '*/25 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    # if there is no artifact to download
    continue-on-error: true

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Create Credentials and Receivers files
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: |
          echo "$CREDENTIALS" > CREDENTIALS.yaml
          echo "$RECEIVERS" > RECEIVERS.txt

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt 

      - name: Download execution timetable from the last forkflow
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: main.yml
          name: exec_timetable
          path: ./.
      
      # delete cat line below, we are using it for debugging purposes
      - name: Run main application
        # if Download exec timetable step failed still run the script
        if: always()
        run: |
          python3 main.py
          cat exec_timetable.json

      - name: Upload execution timetable
        if: always()
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: exec_timetable
          path: exec_timetable.json
          retention-days: 1
