name: Run application

on:
  schedule:
    # Run at every 30th minute from 15 through 59.
    - cron:  '15/30 * * * *'
  push:

  pull_request:

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Credentials and Receivers files
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: |
          echo "$CREDENTIALS" > CREDENTIALS.yaml
          echo "$RECEIVERS" > RECEIVERS.txt

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt 
      
      - name: Run main application
        run: python3 main.py
