name: Run application

on:
  # Run every day at 3:00 UTC time (5:00 Zagreb local time)
  schedule:
    - cron:  '0 3 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Credentials and Receivers files
        run: |
          "$CREDENTIALS" > CREDENTIALS.yaml
          "$RECEIVERS" > RECEIVERS.txt
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
      
      - name: Run main application
        run: python3 main.py
