name: Run application

on:
  schedule:
    # Run every day at 3:45 UTC time (5:45 Zagreb local time)
    - cron:  '45 3 * * *'
  push:
  
  pull_request:

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Credentials and Receivers files
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: |
          echo "$CREDENTIALS" > CREDENTIALS.yaml
          echo "$RECEIVERS" > RECEIVERS.txt

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt 
      
      - name: Run main application
        run: python3 main.py
