name: CI

on:
  schedule:
    - cron:  '0 5 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Check weather
        run: python3 main.py
        env: 
          env_email: ${{ secrets.EMAIL }}
          env_password: ${{ secrets.PASSWORD }}
          env_openWeatherApiKey: ${{ secrets.OPENWEATHERAPIKEY }}
